const bcrypt = require("bcryptjs");

const data = {
  users: [
    {
      name: "Tran Thi Admin",
      email: "admin@admin.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Tran Hoang Cuong",
      email: "cuong@cuong.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Hanes Boys T-Shirt",
      slug: "hanes-boys-t-shirt",
      category: "Shirts",
      image: "product-1.png",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      countInStock: 10,
      numReviews: 10,
      description: "He can feel good about feeling good in these Hanes boys",
      size: ["l", "s", "xl", "xxl"],
      color: ["black", "blue", "yellow", "red", "white"],
      type: "Lastest Product",
    },
    {
      name: "PrinStory Women's Casual Tops Short Sleeve",
      slug: "women-casual-tops-sleeve",
      category: "Shirts",
      image: "product-2.png",
      price: 98,
      brand: "Nike",
      rating: 4.5,
      countInStock: 0,
      numReviews: 7,
      description:
        "Women's shirts include loose short sleeve solid shirt series, fashionable leopard print series and camouflage series, unique V-neck, and T-shirt necessary for summer wardrobe.",
      size: ["l", "s", "xxl"],
      color: ["black", "red", "white"],
      type: "Lastest Product",
    },
    {
      name: "Gildan Men's Crew T-Shirt Multipack",
      slug: "gildan-crew-t-shirt",
      category: "Shirts",
      image: "product-3.png",
      price: 90,
      brand: "Hanes",
      rating: 4,
      countInStock: 4,
      numReviews: 8,
      description:
        "Gildan is one of the world's largest vertically integrated manufacturers of apparel and socks.",
      size: ["l", "s", "xl"],
      color: ["black", "blue", "yellow", "red"],
      type: "Featured Product",
    },

    {
      name: "C9 Champion Boys' Open Leg Knit Pants",
      slug: "c9-champion-pants",
      category: "Pants",
      image: "product-4.png",
      price: 110,
      brand: "C9 Champion",
      rating: 3.5,
      countInStock: 7,
      numReviews: 4,
      description:
        "The Boys' Training Pant from C9 Champion is designed for everyday or sports.",
      size: ["l", "s", "xl", "xxl"],
      color: ["black", "blue", "yellow", "red", "white"],
      type: "Featured Product",
    },
    {
      name: "Hanes Women's French Terry Pocket Pant",
      slug: "hands-french-pocket-pant",
      category: "Pants",
      image: "product-5.png",
      price: 210,
      brand: "Hanes Women's Activewear",
      rating: 5,
      countInStock: 3,
      numReviews: 6,
      description:
        "Hanes women's French terry pocket pant is cotton rich for extra softness. The French terry fabric is smooth outside and brushed inside for extra comfort. Side pockets and adjustable draw cord waist",
      size: ["l", "s", "xl", "xxl"],
      color: ["black", "blue", "yellow", "red", "white"],
      type: "On Sale",
    },
    {
      name: "Southpole Men's Active Basic Jogger Fleece Pants",
      slug: "basic-jogger-fleece-pants",
      category: "Pants",
      image: "product-6.png",
      price: 180,
      brand: "Southpole Young Men's Sportswear",
      rating: 4.5,
      countInStock: 3,
      numReviews: 5,
      description:
        "The Champion Closed Bottom Jersey Pant is Jersey at its best - the ultimate in comfort and durability",
      size: ["s", "xl", "xxl"],
      color: ["blue", "yellow", "white"],
      type: "On Sale",
    },
    {
      name: "adidas Unisex-Child Adizero Football Shoe",
      slug: "adidas-football-shoe",
      category: "Shoes",
      image: "product-7.png",
      price: 300,
      brand: "adidas",
      rating: 4.5,
      countInStock: 2,
      numReviews: 1,
      description:
        "Light on weight, heavy on speed. These juniors' adidas football cleats lock your foot down with a sock-like upper.",
      size: ["l", "s", "xl", "xxl"],
      color: ["black", "blue", "yellow", "white"],
      type: "On Sale",
    },
    {
      name: "PUMA Women's Carina Sneaker",
      slug: "puma-women-carina-sneaker",
      category: "Shoes",
      image: "product-8.png",
      price: 350,
      brand: "PUMA",
      rating: 5,
      countInStock: 5,
      numReviews: 1,
      description:
        "arina l takes inspiration from styles From the 80's - interpreted to fit today's laid-back sneaker look of californian beach towns. ",
      size: ["l", "xl", "xxl"],
      color: ["black", "blue", "yellow", "red", "white"],
      type: "Featured Product",
    },
    {
      name: "PUMA Men's Roma Basic Sneaker",
      slug: "puma-roma-basic-sneaker",
      category: "Shoes",
      image: "product-9.png",
      price: 350,
      brand: "PUMA",
      rating: 5,
      countInStock: 4,
      numReviews: 3,
      description:
        "The Roma is the stuff of PUMA Archive legend with its sport-turned-street style. The original, which debuted in 1968, was geared for sprints, hurdles. ",
      size: ["l", "s", "xl"],
      color: ["black", "blue", "yellow", "red", "white"],
      type: "Lastest Product",
    },
  ],
};

module.exports = data;
