export const SEND_CONTACT_MESSAGE_REQUEST = "SEND_CONTACT_MESSAGE_REQUEST";
export const SEND_CONTACT_MESSAGE_SUCCESS = "SEND_CONTACT_MESSAGE_SUCCESS";
export const SEND_CONTACT_MESSAGE_FAIL = "SEND_CONTACT_MESSAGE_FAIL";
export const RESET_SEND_CONTACT_SUCCESS = "RESET_SEND_CONTACT_SUCCESS";
