export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";
export const PLACE_ORDER_RESET = "PLACE_ORDER_RESET";

export const ORDER_BY_PAYPAL_REQUEST = "ORDER_BY_PAYPAL_REQUEST";
export const ORDER_BY_PAYPAL_SUCCESS = "ORDER_BY_PAYPAL_SUCCESS";
export const ORDER_BY_PAYPAL_FAIL = "ORDER_BY_PAYPAL_FAIL";

//=== Get all order that own by specific user
export const GET_ORDER_LIST_REQUEST = "GET_ORDER_LIST_REQUEST";
export const GET_ORDER_LIST_SUCCESS = "GET_ORDER_LIST_SUCCESS";
export const GET_ORDER_LIST_FAIL = "GET_ORDER_LIST_FAIL";

//=== Get order details
export const GET_ORDER_DETAILS_REQUEST = "GET_ORDER_DETAILS_REQUEST";
export const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS";
export const GET_ORDER_DETAILS_FAIL = "GET_ORDER_DETAILS_FAIL";
export const GET_ORDER_DETAILS_RESET = "GET_ORDER_DETAILS_RESET";

//=== Cancle order
export const ORDER_CANCLE_REQUEST = "ORDER_CANCLE_REQUEST";
export const ORDER_CANCLE_SUCCESS = "ORDER_CANCLE_SUCCESS";
export const ORDER_CANCLE_FAIL = "ORDER_CANCLE_FAIL";
export const ORDER_CANCLE_RESET = "ORDER_CANCLE_RESET";
export const ORDER_CHANGE_STATUS = "ORDER_CHANGE_STATUS";
