export const RATING_REQUEST = "RATING_REQUEST";
export const RATING_SUCCESS = "RATING_SUCCESS";
export const RATING_FAIL = "RATING_FAIL";
export const RATING_RESET = "RATING_RESET";

export const RATING_LIST_REQUEST = "RATING_LIST_REQUEST";
export const RATING_LIST_SUCCESS = "RATING_LIST_SUCCESS";
export const RATING_LIST_FAIL = "RATING_LIST_FAIL";

export const RATING_COMMENTS_REQUEST = "RATING_COMMENTS_REQUEST";
export const RATING_COMMENTS_SUCCESS = "RATING_COMMENTS_SUCCESS";
export const RATING_COMMENTS_FAIL = "RATING_COMMENTS_FAIL";
export const RATING_COMMENTS_RESET = "RATING_COMMENTS_RESET";
