export const SALEOFF_ADD_REQUEST = "SALEOFF_ADD_REQUEST";
export const SALEOFF_ADD_SUCCESS = "SALEOFF_ADD_SUCCESS";
export const SALEOFF_ADD_FAIL = "SALEOFF_ADD_FAIL";

export const SALEOFF_LIST_REQUEST = "SALEOFF_LIST_REQUEST";
export const SALEOFF_LIST_SUCCESS = "SALEOFF_LIST_SUCCESS";
export const SALEOFF_LIST_FAIL = "SALEOFF_LIST_FAIL";
